import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { BDCounter } from '../components/dashboard-items/DBCounter'
import { Layout } from '../components/Layout'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className={"flex justify-evenly w-full h-screen bg-slate-500 p-4"}>
          <BDCounter />
          <BDCounter />
          <BDCounter />
        </div>
      </Layout>
    </div>
  )
}

export default Home
